### ISSUE TITLE
Knife visual bug

### ISSUE THREAD

**Issue by Maxi605** [GuskiS/Trouble-in-Terrorist-Town#12]
If you survive the round with a knife on your hands and have the weapon switch turned off you will spawn with your crowbar but your world model (I think is that the one), that all players see on your hands is the knife one.

**Comment by GuskiS** [comment]
This has been notified to me already. One thing tho, it needs to have `hud_fastswitch` turned off to test this. Haven't tested it tho, but that is what might be the issue.

**Comment by GuskiS** [comment]
Issue was with `_cl_autowepswitch 0` command.

**Comment by Maxi605** [comment]
Fixes the bug, perfect!
