### ISSUE TITLE
Windows Server Crash

### ISSUE THREAD

**Issue by Rivotril605** [GuskiS/Trouble-in-Terrorist-Town#2]
Hello, i'm using the lastest version of HLDS with this mod (also the last version of it) with 1.8.2 AMX and i get a crash randomly when players attack each other (i think Traitor vs innocent) server crash and send APPCRASH

Update:

New error,

![1](https://cloud.githubusercontent.com/assets/23621914/20467923/3150a054-af6f-11e6-82c1-48122f3b437b.jpg)
![2](https://cloud.githubusercontent.com/assets/23621914/20467924/31533e04-af6f-11e6-8c7d-ee9e91aeb9b3.jpg)
![3](https://cloud.githubusercontent.com/assets/23621914/20467925/3156bb2e-af6f-11e6-87f2-da77e843deec.jpg)

**Comment by GuskiS** [comment]
The spanish language doesn't help. :smile: But the issue could be solved(less common) on amxmodx 1.8.3. Atleast on my linux server it is working fine.
