### ISSUE TITLE
Deactivation Kit doesn't work

### ISSUE THREAD

**Issue by Maxi605** [GuskiS/Trouble-in-Terrorist-Town#33]
Basicly if you're a detective and buy a deactivation kit (for the C4) doesn't work

what i mean is, you want to defuse a C4 with the defuse kit and it just doesn't work, you have the 50-50 chance

**Comment by GuskiS** [comment]
I replied here: https://github.com/GuskiS/Trouble-in-Terrorist-Town/pull/20#issuecomment-409293629
