### ISSUE TITLE
C4 Sprite Bug

### ISSUE THREAD

**Issue by Maxi605** [GuskiS/Trouble-in-Terrorist-Town#5]
Sometimes after the C4 explodes the sprite of the C4 gets transfered to a random dropped weapon, if possible i screenshot and send it to you.

**Comment by GuskiS** [comment]
`random dropped weapon` this could lead me on something.
When someone drops weapon, that weapon gets new entity number. There could be case when C4 explodes, weapon is dropped, and sprite just checks if this entity exists and it does cause of new weapon.

Nice, will investigate this more 👍
