### ISSUE TITLE
Newton doesn't reset on new round

### ISSUE THREAD

**Issue by Maxi605** [GuskiS/Trouble-in-Terrorist-Town#9]
When you shoot somebody with a Newton, the player has "something" that tells the mod that he was shooted by "x" player, when the round endes that "something" doesn't get removed, on the next rounds the "something" is still active, so if somebody dies of hitting the ground or suicide it will say that the "X" player killed him, i believe a good solution to that will be to leave the "something" for 5 seconds and remove it, also remove it on Round End/Restart.

**Comment by GuskiS** [comment]
Will check, nice one 👍
